In [1]:
import numpy as np
import cv2

In [6]:
a = np.array([1,2,3])
b = np.ones([2,2,3])
a.shape, b.shape, (a*b).shape

((3,), (2, 2, 3), (2, 2, 3))

In [11]:
(a*b)[0,0,0]

1.0

In [12]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
exec('x=1+2')

In [39]:
'{}+{}=2'.format(1,1)

'1+1=2'

In [44]:
x = np.arange(0,100,1)
X,Y = np.array(np.meshgrid(x,x))
X.shape, Y.shape

((100, 100), (100, 100))

In [23]:
def dis(x):
    return (np.sqrt((x[0]-50)**2 + (x[1]-50)**2) < 10)
list(filter(dis, inds))

[array([43., 43.]),
 array([44., 44.]),
 array([45., 45.]),
 array([46., 46.]),
 array([47., 47.]),
 array([48., 48.]),
 array([49., 49.]),
 array([50., 50.]),
 array([51., 51.]),
 array([52., 52.]),
 array([53., 53.]),
 array([54., 54.]),
 array([55., 55.]),
 array([56., 56.]),
 array([57., 57.])]

In [21]:
def dis(x):
    return (np.sqrt(np.sum(x-[50,50]) < 10)
dis(inds)

array([False, False])

In [51]:
list(zip([1,2,3],[1,2,3]))

[(1, 1), (2, 2), (3, 3)]

In [52]:
X

array([[ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99],
       ...,
       [ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99]])

In [53]:
Y

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [97, 97, 97, ..., 97, 97, 97],
       [98, 98, 98, ..., 98, 98, 98],
       [99, 99, 99, ..., 99, 99, 99]])

In [ ]:
def dis(x,y):
    return (np.sqrt((x[0]-50)**2 + (x[1]-50)**2) < 10)

In [79]:
injection = np.zeros([100, 100, 3])
r = 1
# injection kernel
injection_kernel = np.zeros([2*r, 2*r])
for i in range(2*r):
    for j in range(2*r):
        if (i-r)**2 + (j-r)**2 <= r**2:
            injection_kernel[i, j] = 1
injection[x-r:x+r, y-r:y+r, 0] += injection_kernel

In [86]:
r = 8
# injection kernel
injection_kernel = np.zeros([2*r, 2*r])
for i in range(2*r):
    for j in range(2*r):
        if (i-r)**2 + (j-r)**2 <= r**2:
            injection_kernel[i, j] = 1
injection[x-r:x+r, y-r:y+r, 1] += injection_kernel

In [87]:
np.sum(injection)

440.0

In [88]:
injection.shape

(100, 100, 3)

In [90]:
[[]]*3

[[], [], []]